name: build

on: push
  # push:
  #   tags:
  #     - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cleanup artifacts
      run: yarn rimraf "build/!(*.AppImage|*.snap|*.exe|*.dmg)"
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: build
